name: Node.js CI

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
        working-directory: frontend
    
      - name: Run linting
        run : npm run lint
        working-directory: frontend

      - name: Run audit
        run : npm audit
        working-directory: frontend
        continue-on-error: true

      - name: Set up docker
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker images
        run : docker compose up --build

      - name: Run Cypress tests with React server
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60
